spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3360/myproj?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  resources:
    static-locations : file:src/main/resources/static/